### ISSUE TITLE
[Bug] => Crashed when reading Chinese

### ISSUE THREAD

**Issue by opabravo** [0xInfection/XSRFProbe#10]
``` 
[+] Crawling :> http://www.xxxxx.xx.xxx.xx/xxx.pdf
Traceback (most recent call last):
  File "xsrfprobe.py", line 14, in <module>
    xsrf_main() # the true start of the program ;)
  File "/home/opabravo/sec/XSRFProbe/core/xsrf_main.py", line 57, in xsrf_main
    soup=crawler.process(web) # start the parser
  File "/home/opabravo/sec/XSRFProbe/modules/Crawler_Handler.py", line 53, in process
    query = self.opener.open(url) # open it
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1142, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 984, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-22: ordinal not in range(128)
```

**Comment by 0xInfection** [comment]
Seems to be a serious dependency issue. Will try to get a better workaround.

**Comment by 0xInfection** [comment]
XSRFProbe v2 workflow is entirely different. Can you confirm whether the new version is immune to this bug?

**Comment by opabravo** [comment]
Unfortunately, it still returns ascii error

```
[-] Endpoint SameSite Flag Cookie Validation Not Present!
 [-] Heuristic(s) reveal endpoint might be  VULNERABLE  to CSRFs...
 [+] Possible CSRF Vulnerability Detected : http://www.xxxxx.xxx.xxx.xxxx/index-4-parent.aspx!
 [!] Possible Vulnerability Type:  No SameSite Flag on Cookies 
 [-] Skipping persistence checks as no cookie value supplied...
 [!] Retrieving all forms on http://www.xxxxx.xxx.xxx.xx/tw/index-4-parent.aspx...
 [+] Crawling :> http://www.xxxxx.xxx.xxx.xx/tw/doc/daan-buildings.pdf
 [+] Crawling :> http://www.xxxxx.xxx.xxx.xx/tw/doc/calendar-1.pdf
 [+] Crawling :> http://www.xxxxx.xxx.xxx.xx/tw/doc/calendar-2.pdf
 [+] Crawling :> http://www.xxxxx.xxx.xxx.xx/tw/doc/note.pdf
Traceback (most recent call last):
  File "xsrfprobe.py", line 13, in <module>
    main.Engine()  # the true start of the program ;)
  File "/home/opabravo/sec/XSRFProbe/core/main.py", line 102, in Engine
    soup = crawler.process(web)  # Start the parser
  File "/home/opabravo/sec/XSRFProbe/modules/Crawler.py", line 64, in process
    query = self.opener.open(url)  # Open it (to check if it exists)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1142, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 984, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-22: ordinal not in range(128)
```

**Comment by 0xInfection** [comment]
I made some commits which should fix the bug. Can you try out the [Fixing-#10](https://github.com/0xInfection/XSRFProbe/tree/Fixing-%2310) branch and see if it's working?

**Comment by opabravo** [comment]
```
 [+] Crawling :> http:/index.aspx
Traceback (most recent call last):
  File "/home/opabravo/XSRFProbe-Fixing-10/modules/Crawler.py", line 65, in process
    query = get(url)  # Open it (to check if it exists)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'http:/index.aspx': No schema supplied. Perhaps you meant http://http:/index.aspx?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "xsrfprobe.py", line 13, in <module>
    main.Engine()  # the true start of the program ;)
  File "/home/opabravo/XSRFProbe-Fixing-10/core/main.py", line 102, in Engine
    soup = crawler.process(web)  # Start the parser
  File "/home/opabravo/XSRFProbe-Fixing-10/modules/Crawler.py", line 72, in process
    except (urllib.exceptions.HTTPError, urllib.exceptions.URLError) as msg:  # Incase there isan exception connecting to Url
AttributeError: module 'urllib' has no attribute 'exceptions'
```

**Comment by 0xInfection** [comment]
Oh no, another error. I pushed a commit. It should fix both. Can you test the branch again? If this time you get some error, can you let me know the site on which you're testing? If it's sensitive, you can send it to me via my email.

**Comment by opabravo** [comment]
Mail sent
error:
```
Crawling :> http:/index.aspx
Traceback (most recent call last):
  File "C:\Users\GOD\Desktop\XSRFProbe-Fixing-10\modules\Crawler.py", line 65, in process
    query = get(url)  # Open it (to check if it exists)
  File "C:\Users\GOD\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\GOD\AppData\Roaming\Python\Python36\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\GOD\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "C:\Users\GOD\AppData\Roaming\Python\Python36\site-packages\requests\sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\GOD\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "C:\Users\GOD\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 366, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'http:/index.aspx': No schema supplied. Perhaps you meant http://http:/index.aspx?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GOD\Desktop\XSRFProbe-Fixing-10\xsrfprobe.py", line 13, in <module>
    main.Engine()  # the true start of the program ;)
  File "C:\Users\GOD\Desktop\XSRFProbe-Fixing-10\core\main.py", line 102, in Engine
    soup = crawler.process(web)  # Start the parser
  File "C:\Users\GOD\Desktop\XSRFProbe-Fixing-10\modules\Crawler.py", line 72, in process
    except (urllib.error.HTTPError, urllib.exceptions.URLError) as msg:  # Incase there isan exception connecting to Url
AttributeError: module 'urllib' has no attribute 'exceptions'
```

**Comment by 0xInfection** [comment]
I added some major commits which fixes your bug. I fully tested your site against the latest version. It works perfectly. Check out the `master` branch and confirm it. If yes, I would label this issue as resolved.
