### ISSUE TITLE
Cookies and headers not added to all requests

### ISSUE THREAD

**Issue by Freedzone** [0xInfection/XSRFProbe#39]
#### Describe the bug
There are a couple of requests in the **core/main.py(86:87)** that are issued before parameters processing, thus provided cookies and headers are not applied to them that can cause httperror exceptions (401 in my case).

#### Command You Used
```
xsrfprobe --no-verify -vv --malicious --cookie 'session=gGYCowmFLMcxL1dnloxmiVqN7qO5ILak' -u https://ac171f651e1e1a0e80c94df100620040.web-security-academy.net/email
```

#### Full Stack Trace Error

```
 [!] Testing site ac171f651e1e1a0e80c94df100620040.web-security-academy.net status...
 [+] Site seems to be up!
 [!] Testing email endpoint status...
 [+] Endpoint seems to be up!
Traceback (most recent call last):
  File "/usr/local/bin/xsrfprobe", line 4, in <module>
    __import__('pkg_resources').run_script('xsrfprobe==2.2.0', 'xsrfprobe')
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/xsrfprobe-2.2.0-py3.7.egg/EGG-INFO/scripts/xsrfprobe", line 15, in <module>
  File "/usr/local/lib/python3.7/dist-packages/xsrfprobe-2.2.0-py3.7.egg/xsrfprobe/xsrfprobe.py", line 14, in startEngine
  File "/usr/local/lib/python3.7/dist-packages/xsrfprobe-2.2.0-py3.7.egg/xsrfprobe/core/main.py", line 90, in Engine
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

#### Potential cause or fix
Add headers and cookies to first requests.
```   
    hdrs = [('Cookie', ','.join(cookie for cookie in config.COOKIE_VALUE))]
    [hdrs.append((k, v)) for k, v in config.HEADER_VALUES.items()]
    resp1.addheaders = resp2.addheaders = hdrs;
    resp1.open(init1)  # Makes request as User2
    resp2.open(init1)  # Make request as User1
```

#### Environment:
- OS: [Kali Rolling 2019.4]
- Python version: [v3.7.5]

#### Some Questions

- [x] I am using the latest version of XSFRProbe.
- [x] I installed the dependecies using `pip3` instead of `pip`.
- [x] I have read the documentation before submitting this issue.
- [x] I have checked the other issues to see if someone reported this before.

**Comment by 0xInfection** [comment]
Hi @Freedzone,

Many thanks for pulling this issue up. I have identified the bug and pushed a fix on the [`dev`](https://github.com/0xInfection/XSRFProbe/tree/dev) branch. Please test out the branch before I merge and make a release. Do keep these bugs coming whenever you find a issue. Open source thrives on these!

**Comment by Freedzone** [comment]
Hey no problems man ). The fix works for me. Thanks.
