### ISSUE TITLE
Tool does not work if you insert the localhost as the url 

### ISSUE THREAD

**Issue by DasJennir** [0xInfection/XSRFProbe#45]
#### Describe the bug
While trying to scan a website on my local machine http://127.0.0.1:3000 the tool does not seem to work, it displays to me an error that says " Domain 127.0.0.1 didn't match any existing TLD name!".

#### Command You Used
I have tried two commands:
sudo xsrfprobe -u http://127.0.0.1:3000
sudo xsrfprobe -u http://localhost:3000

#### Full Stack Trace Error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/xsrfprobe/core/options.py", line 170, in <module>
  File "/usr/lib/python3/dist-packages/tld/utils.py", line 366, in get_fld
    domain_parts, non_zero_i, parsed_url = process_url(
  File "/usr/lib/python3/dist-packages/tld/utils.py", line 316, in process_url
    raise TldDomainNotFound(domain_name=domain_name)
tld.exceptions.TldDomainNotFound: Domain 127.0.0.1 didn't match any existing TLD name!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xsrfprobe", line 4, in <module>
    __import__('pkg_resources').run_script('xsrfprobe==2.3.1', 'xsrfprobe')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/EGG-INFO/scripts/xsrfprobe", line 15, in <module>
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/xsrfprobe/xsrfprobe.py", line 13, in startEngine
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/xsrfprobe/core/main.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/xsrfprobe/core/options.py", line 176, in <module>
AttributeError: 'NoneType' object has no attribute 'group'

```
#### Potential cause or fix

Maybe add an exception to the localhost domain?

#### Environment:
- __OS__: [ Kali Rolling 2020.2 on Dockers]
- __Python version__: [Python 3.8.3]

#### Other stuff
Besides from that, I would like to thank you for making such a cool tool !!!

**Comment by 0xInfection** [comment]
Thanks for pulling this up! Realized it was a buggy regex for validating the IP which didn't validate `127.0.x.x` class IPs. d59622e probably does the trick.

Can you test out the branch [`localfix`](https://github.com/0xInfection/XSRFProbe/tree/localfix) and let me know if the fix works properly for you?

**Comment by DasJennir** [comment]
Sorry mate but the error still occurs I have tried different environments but it does not seem to fix it, I have done the update by using the --update flag, and also a fresh install of the tool but none of these options worked for me. Here is the traceback:

```
VMWARE: sudo xsrfprobe --url http://127.0.0.1:3000
```
```
  XSRFProbe, A Cross Site Request Forgery Audit Toolkit

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe/core/options.py", line 170, in <module>
    os.makedirs('xsrfprobe-output/'+tld.get_fld(config.SITE_URL))
  File "/usr/lib/python3/dist-packages/tld/utils.py", line 366, in get_fld
    domain_parts, non_zero_i, parsed_url = process_url(
  File "/usr/lib/python3/dist-packages/tld/utils.py", line 316, in process_url
    raise TldDomainNotFound(domain_name=domain_name)
tld.exceptions.TldDomainNotFound: Domain 127.0.0.1 didn't match any existing TLD name!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xsrfprobe", line 15, in <module>
    xsrfprobe.startEngine()
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe/xsrfprobe.py", line 13, in startEngine
    from xsrfprobe.core import main  # import stuff
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe/core/main.py", line 34, in <module>
    from xsrfprobe.core.options import *
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe/core/options.py", line 176, in <module>
    direc = re.search(IP, config.SITE_URL).group(0)
AttributeError: 'NoneType' object has no attribute 'group'`
```
```
DOCKERS: sudo  xsrfprobe  --url http://127.0.0.1:3000
```
```
    XSRFProbe, A Cross Site Request Forgery Audit Toolkit

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xsrfprobe-2.3.1-py3.6.egg/xsrfprobe/core/options.py", line 170, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tld/utils.py", line 437, in get_fld
    parser_class=parser_class
  File "/usr/local/lib/python3.6/dist-packages/tld/utils.py", line 381, in process_url
    raise TldDomainNotFound(domain_name=domain_name)
tld.exceptions.TldDomainNotFound: Domain 127.0.0.1 didn't match any existing TLD name!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xsrfprobe", line 4, in <module>
    __import__('pkg_resources').run_script('xsrfprobe==2.3.1', 'xsrfprobe')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/xsrfprobe-2.3.1-py3.6.egg/EGG-INFO/scripts/xsrfprobe", line 15, in <module>
  File "/usr/local/lib/python3.6/dist-packages/xsrfprobe-2.3.1-py3.6.egg/xsrfprobe/xsrfprobe.py", line 13, in startEngine
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/xsrfprobe-2.3.1-py3.6.egg/xsrfprobe/core/main.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/xsrfprobe-2.3.1-py3.6.egg/xsrfprobe/core/options.py", line 176, in <module>
AttributeError: 'NoneType' object has no attribute 'group'
 ```

**Comment by 0xInfection** [comment]
Hi, a clean install via git should properly install the tool. Please test the `localfix` branch and not the `master` branch as the changes have not been merged into master yet. Use the following git command to clone the localfix branch explicitly.
```
git clone https://github.com/0xinfection/xsrfprobe -b localfix
```

**Comment by DasJennir** [comment]
Nice, it does seem to work now, but the only thing is that when the tools start to check the status of the website it always says that the site seems to be down I have tried different ports and 3 different machines.
If you want to here are the links for the machines that I have used: 
https://github.com/WebGoat/WebGoat   
https://hub.docker.com/r/bkimminich/juice-shop/


Outcome:

   [---]            XSRFProbe, A Cross Site Request Forgery Audit Toolkit          [---]
   [---]                                                                           [---]
   [---]                       ~  Author : Pinaki Mondal  ~                        [---]
   [---]                      ~  github.com / 0xInfection  ~                       [---]
   [---]                                                                           [---]
   [---]                           ~  Version 2.3.1  ~                             [---]

 [!] Testing site 127.0.0.1:3000 status...
 [-] Site seems to be down...

**Comment by 0xInfection** [comment]
Sure! I'll give it a try and update you with a fix.

**Comment by 0xInfection** [comment]
Hi, 
I tested this on WebGoat on my own machine, and it seems to work flawlessly. Just make sure to mention the right scheme you are using to connect, if you are using `https` make sure to mention the URL like this: `xsrfprobe -u https://127.0.0.1:3000 --cookie PHPSESSID=xxxxxxxx`.

**Comment by DasJennir** [comment]
Got it, thank you for all the attention, and support, once again thank you for such a cool tool !!!

**Comment by luceat-lux-vestra** [comment]
This is not applied to the current release version on PyPi(pip),  
clone and setup manually if you need to test localhost.

It would be good to release a new version.
