### ISSUE TITLE
--exclude command doesnt work

### ISSUE THREAD

**Issue by CookiePackage** [0xInfection/XSRFProbe#48]
#### Describe the bug
When using --exclude command the tool breaks

#### Command You Used
xsrfprobe -u "http://192.168.1.1/cgi-bin/luci/admin/status" --cookie "sysauth=a0ab02bc860607be5aa506752c1aaf05" --crawl -d 10 -t 10 -E logout/

#### Full Stack Trace Error

Traceback (most recent call last):
  File "/usr/local/bin/xsrfprobe", line 4, in <module>
    __import__('pkg_resources').run_script('xsrfprobe==2.3.1', 'xsrfprobe')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/EGG-INFO/scripts/xsrfprobe", line 15, in <module>
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/xsrfprobe/xsrfprobe.py", line 13, in startEngine
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/xsrfprobe/core/main.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/xsrfprobe-2.3.1-py3.8.egg/xsrfprobe/core/options.py", line 148, in <module>
AttributeError: 'list' object has no attribute 'strip'

#### Potential cause or fix
[Do you know what could be causing the problem or how to fix it?]

#### Environment:
- __OS__: [Ubuntu 20.04.1 LTS]
- __Python version__: [e.g. v3.8.5]

#### Some Questions

- [x] I am using the latest version of XSFRProbe. Yes: v2.3.1
- [x] I installed the dependecies using `pip3` instead of `pip`. yes
- [x] I have read the documentation before submitting this issue. yes
- [x] I have checked the other issues to see if someone reported this before. yes

#### Other stuff
[Something else you want the author to know?]

**Comment by HACKE-RC** [comment]
I've tried fixing this error, I now got another error. Trying to fix it, then I will open a PR

**Comment by HACKE-RC** [comment]
xsrfprobe-output/webscantest.com/errored.log:1:(i) http://www.webscantest.com/csrf/csrfpost.php/ -> list.remove(x): x not in list

Why am i getting this :(
