### ISSUE TITLE
[Bug] => NameError: global name 'cookielib' is not defined

### ISSUE THREAD

**Issue by iamprbkr** [0xInfection/XSRFProbe#5]
I am using python2.7 to run the code from the repository.
The cookie values are not accepted if given in input. If there is no value given 
```
Enter target address :> http://xyz.in
 [!] Testing site status...
 [+] Site seems to be up!
 [$] Got any cookies? [Enter for None] :> 
Traceback (most recent call last):
  File "xsrfprobe.py", line 14, in <module>
    xsrf_main() # the true start of the program ;)
  File "/home/XSRFProbe/core/xsrf_main.py", line 28, in xsrf_main
    Cookie0 = cookielib.CookieJar() # cookies ummm...
NameError: global name 'cookielib' is not defined
```
Do let me know if you need additional information.

**Comment by 0xInfection** [comment]
Fixed! 🙂 Thanks for the issue.

**Comment by iamprbkr** [comment]
Thanks a lot for the fix!!! Keep up the good work :+1:
