### ISSUE TITLE
Import Issue in startEngine

### ISSUE THREAD

**Issue by Nittonull** [0xInfection/XSRFProbe#52]
Traceback (most recent call last):
  File "/home/Username/.local/bin/xsrfprobe", line 15, in <module>
    xsrfprobe.startEngine()
  File "/home/Username/.local/lib/python2.7/site-packages/xsrfprobe/xsrfprobe.py", line 13, in startEngine
    from xsrfprobe.core import main  # import stuff
ImportError: No module named core

Please Help in solving this issue

**Comment by 0xInfection** [comment]
Use Python 3.
